Kong/koko

docs/koko-vs-kong.md
go.mod
go.sum
internal/config/db.go
internal/config/types.go
internal/db/db.go
internal/db/db_test.go
internal/db/migrate.go
internal/db/persister.go
internal/db/sql/mysql/0001_init.down.sql
internal/db/sql/mysql/0001_init.up.sql
internal/persistence/driver.go
internal/persistence/mysql/mysql.go
internal/persistence/mysql/options.go
internal/persistence/mysql/tx.go
internal/test/util/db.go
internal/test/util/store.go
koko.yaml

This change introduces support for MySQL >= 8.0.17.
—
**Work remaining/completed:**
- See #450.
- See #458.
- I tested MySQL with their minimum supported version of 8.0.23 and the latest supported version of 8.0.30. All works as expected.

feat: MySQL DB support

---

.github/workflows/integration.yaml
.github/workflows/lint.yaml
.github/workflows/security.yaml
.github/workflows/unit.yaml

This matches our build logic, as we also currently build using the latest Go 1.19 version as well.
This is done to correct the following vulnerability:
```
Vulnerability #1: GO-2022-1039
Programs which compile regular expressions from untrusted
sources may be vulnerable to memory exhaustion or denial of
service. The parsed regexp representation is linear in the size
of the input, but in some cases the constant factor can be as
high as 40,000, making relatively small regexps consume much
larger amounts of memory. After fix, each regexp being parsed is
limited to a 256 MB memory footprint. Regular expressions whose
representation would use more space than that are rejected.
Normal use of regular expressions is unaffected.
Found in: regexp/syntax@go1.19.1
Fixed in: regexp/syntax@go1.19.2 …
```

chore: updating govulncheck to run with the latest Go 1.19 version

---

internal/plugin/validators/badtestdata/embed.go
internal/plugin/validators/badtestdata/lua-tree/share/lua/5.1/validate-invalid-json.lua
internal/plugin/validators/lua_validator.go
internal/plugin/validators/lua_validator_test.go

Right now, if an unexpected error like a panic happens during plugins validation via goks, an Internal Error is returned to the user with no explanation about the nature of the error. For example:
```
{
"code": 9,
"message": "unmarshal kong plugin validation error: invalid character 'r' looking for beginning of value"
}
```
This commit makes sure Koko logs the original error and returns a slightly nicer 400 to the user, like:
```
{
"code": 3,
"details": [
{
"@type": "type.googleapis.com/kong.admin.model.v1.ErrorDetail",
"messages": [
"(ip-restriction) unknown plugin validation error, please file a bug with Kong Inc"
]
}
],
"message": "validation error"
}
```

fix: improve unexpected plugins validation errors handling

---

docs/assets/docker-compose.yml

Use a "true" string instead of a boolean in compose environment.
Makes YAML less unhappy about:
```
$ docker-compose up     
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.koko.environment.KOKO_DATABASE_SQLITE_IN_MEMORY contains true, which is an invalid type, it should be a string, number, or a null
```

fix: correct compose type

---

.github/workflows/dev-builds.yaml

This replaces set-output usage with the new environment variable files that are available with GitHub Actions.
see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

chore: fix set-output usage due to deprecation

---

.github/workflows/dev-builds.yaml
.github/workflows/integration.yaml
.github/workflows/label-check.yaml
.github/workflows/lint.yaml
.github/workflows/release-push.yaml
.github/workflows/security.yaml
.github/workflows/unit.yaml

This updates the display names which are visible on GitHub Actions. The current names visible in the UI add to confusion when running any of them manually; the goal here is to remove that confusion.

chore: update workflow display names for GitHub Actions

---

.github/workflows/dev-builds.yaml
.github/workflows/release-push.yaml

The GitHub UI does not have enough space to allow for the full name of the workflow to be displayed nor does it have a way currently to change the size of the panel.

chore: shorten Docker image workflow names

---

internal/server/kong/ws/config/compat/compatibility_table.go
internal/server/kong/ws/config/version_compatibility.go
internal/server/kong/ws/config/version_compatibility_test.go
internal/test/e2e/plugins.go
internal/test/e2e/version_compatibility_test.go

Fixes a bug where if either a pre-function or post-function plugin config contained config.access
and was < v3.0.0 with a downstream dp > v3.0.0, the access field is overwritten with the empty array
and is rejected by the dp.
Generally: updates the processing performed on plugin configs during version compatibility updates.
Previously, an empty array value would overwrite an existing target array value when performing the update.
This is an edge case as the target value being overwritten is on a field that does not exist
for the control-plane version but does exist for the data-plane config.
More concretely:
* Version < v3.0.0
* creates a default value functions: [] when functions is undefined
* access field does not exist (but can be defined by user)
* Version > v3.0.0
* Creates an …

fix: conditionally ignore empty value updates

---

internal/resource/route.go
internal/resource/route_test.go
internal/resource/sni.go
internal/resource/sni_test.go

Current validation allows setting IP addresses as
SNI's `name`, which causes the DP to reject the configuration
as that's now allowed:
```
- in entry 1 of 'routes':
in 'snis':
- in entry 1 of 'snis': must not be an IP, context: ngx.timer
```
This commit makes sure that no IP or port can be set for
SNI's `name`.
Sample calls to Kong for both `snis` and `routes`:
```
$ echo '
paths:
- /
snis:
- localhost:8080
' | y2j | http ":8001/routes"
HTTP/1.1 400 Bad Request
{
"code": 2,
"fields": {
"snis": [
"must not have a port"
]
},
"message": "schema violation (snis.1: must not have a port)",
"name": "schema violation"
}
$ echo '
paths:
- /
snis:
- 1.2.3.4
' | y2j | http ":8001/routes"
HTTP/1.1 400 Bad Request
{
"code": 2,
"fields": {
"snis": [
"must not be an IP"
]
},
"message": "schema violation …
```

fix: expand SNI validation to not allow IPs

---

internal/resource/ca_certificate.go
internal/resource/ca_certificate_test.go
internal/server/admin/ca_certificate_test.go
internal/test/seed/resource.go
internal/test/util/util.go

Right now the CA certs validation is only checking whether the cert's Basic Constraints attribute is valid or not, while it should also check whether the 'CA' basic constraint is set and fail if it's not.

fix: CA certs validation let certs with CA=False pass

---

internal/cmd/run.go
internal/cmd/run_test.go
internal/plugin/validators/lua_validator_test.go
internal/server/admin/helpers_test.go
internal/server/admin/node_test.go
internal/server/admin/service_test.go
internal/server/kong/ws/manager.go
internal/server/kong/ws/manager_test.go
internal/server/kong/ws/relay_event_streamer_test.go
internal/server/relay/event_service_test.go
internal/server/relay/status_service_test.go
internal/store/store.go
internal/store/store_test.go
internal/store/timestamp_test.go

As briefly spoken about [here](https://github.com/Kong/koko/pull/472#discussion_r996220118), we're introducing the ability to get the cluster ID on the object store, which can mostly be used for things like unit testing & general observability like logging.
This is broken up into two commits to allow for easier review.

feat: get cluster ID on object store

---

internal/gen/grpc/kong/admin/service/v1/schemas.pb.go
internal/gen/grpc/kong/admin/service/v1/schemas.pb.gw.go
internal/gen/swagger/koko.swagger.json
internal/grpc/proto/kong/admin/service/v1/schemas.proto
internal/plugin/validators/lua_validator.go
internal/plugin/validators/lua_validator_test.go
internal/server/admin/schemas_test.go

Corrects an issue where the `POST /v1/schemas/json/plugin/validate` endpoint could not validate custom plugins properly. This also corrects an issue where custom plugin schemas were not pulled in when a cluster ID is not provided.
This is in draft status as we should update the tests as well.

fix: honoring the cluster ID when validating plugins

---

internal/test/e2e/vault_test.go
internal/test/kong/docker.go
internal/test/kong/run.go

This commit add an e2e test making sure that
secrets management using the Vault entity works as expected. This is done by injecting some environment variables in the DP (serving as recrets), create a Vault entity to 'stores' those secrets and have a
Certificate referencing the secrets.

tests: add e2e for secrets management

---

internal/server/admin/schemas_service.go
internal/server/admin/schemas_test.go

Right now Koko requires a schema to include all required fields in order to pass validation via the `/v1/schemas/json/<entity>/validate` endpoint, regardless of these fields having schema defaults that are injected at run time.
For example:
```
$ echo '
id: 7f27869a-be49-406b-83f0-1c14becc1508
name: foo
host: example.com
path: /
' | y2j | http ":3000/v1/schemas/json/service/validate"
HTTP/1.1 400 Bad Request
{
"code": 3,
"details": [
{
"@type": "type.googleapis.com/kong.admin.model.v1.ErrorDetail",
"messages": [
"missing properties: 'protocol', 'port', 'connect_timeout', 'read_timeout', 'write_timeout'"
],
"type": "ERROR_TYPE_ENTITY"
}
],
"message": "validation error"
}
```
This doesn't match the behaviour with Kong, which would let this payload pass because of the existing schema default …

feat: process schema defaults before peforming schema validation

---

internal/server/kong/ws/config/configuration.go
internal/server/kong/ws/manager.go
internal/server/kong/ws/node.go
internal/server/kong/ws/payload.go
internal/server/kong/ws/server.go

Adds the following metrics:
* duration (s) to establish initial connection between dp and cp
* duration (s) of individual config mutations
* duration (s) of total aggregate config mutations
* duration (s) of version compat cache miss path

feat: add dataplane metrics for control plane

---

internal/plugin/schemas/zipkin.lua
internal/server/kong/ws/config/compat/compatibility_table.go
internal/test/e2e/plugins.go
internal/test/e2e/version_compatibility_test.go

Adds `http_response_header_for_traceid`for zipkin.
See https://github.com/Kong/kong/pull/9173

feat: zipkin traceid response header

---

internal/gen/jsonschema/schemas/route.json
internal/resource/route.go
internal/resource/route_test.go
internal/server/admin/route_test.go
internal/test/e2e/basic_test.go

This change alters the `Route` entity to allow the `Hosts` field to take in wildcard hostnames, e.g.: `*.example.com`.

fix: updating route resource to accept wildcard hostnames

---

internal/server/kong/ws/config/compat/compatibility_table.go
internal/server/kong/ws/config/compat/compatibility_table_test.go

Adds a check on config.http_response_header_for_traceid for the zipkin plugin. Change tracking is conditionally ignored when this field is set to the default value (nil).

fix: Disable Change Tracking for Zipkin TraceID Header

---

go.mod
go.sum
internal/config/config_test.go
internal/config/db.go
internal/config/testdata/good-0.yaml
internal/db/db_test.go
internal/persistence/driver.go
internal/persistence/postgres/options.go
internal/persistence/postgres/pool.go
internal/persistence/postgres/pool_test.go
internal/persistence/postgres/postgres.go
internal/persistence/postgres/tx.go
internal/test/util/db.go

This PR is a refactor of the postgres persistence layer. Changes:
* Use the `pgxpool.Pool` interface to execute query instead of the built-in `database/sql`
* Add basic pooling options to the postgres config options.
* Make the postgres Pool plugable under the hood.

refactor: use pgxpool.Pool instead of database/sql for postgresql

---

internal/model/object.go
internal/model/registry.go
internal/store/index.go

This introduces a new interface that objects can implement in order to influence its behavior within the persistence store. The primary use-case for this right now is to override the object cascading functionality upon deletions.
This change is primarily being introduced for the ongoing consumer groups effort, though this functionality may come in handy later on.

feat: introducing customizable model object cascading functionality

---

go.mod
internal/model/object.go
internal/model/object_test.go
internal/resource/ca_certificate.go
internal/resource/route.go
internal/resource/service.go
internal/store/index.go
internal/store/store.go

This introduces the ability to validate any indexes at runtime during the creation/updation process. There were some issues where empty indexes were being improperly provided and were being ignored by the `ObjectStore.indexKV()` method.
It's better to be explicit here, so this change introduces proper validation for the indexes and also patches up this seemingly confusing issue.

fix: validate object indexes

---

internal/model/object.go
internal/model/object_test.go
internal/store/index.go
internal/store/store.go

This allows the ability to bypass the default managed index behavior that the persistence store provides, in order to explicitly set whether index(es) should be created and/or removed.
This allows the ability to add & remove foreign relations without needing to know all foreign relations that exist on the given entity.

feat: introducing concept of unmanaged indexes

---

internal/persistence/mysql/mysql.go
internal/persistence/postgres/postgres.go
internal/persistence/sql.go
internal/persistence/sqlite/sqlite.go
internal/store/opts.go
internal/store/store.go

This introduces a change to the persistence store that allows callers to list the foriegn resources themselves. Currently, a `ListFor()` call exists that allows listing resource(s) that have the associated foreign key index, although listing the other way around was not previously supported.

feat: allowing persistence store to list foreign objects

---

internal/store/store.go

This change implements the ability to update just the foreign keys related to an object. This functionality is required for the recent consumer groups implementation.

feat: introducing foreign key management support to persistence store

---

internal/model/json/schema/formats.go
internal/model/json/schema/formats_test.go

This validator accepts only PEM (PKCS8) public key, and not PEM+RSA (PKCS1) keys.

feat: add a pkix (pkcs8) json validator

---

internal/server/kong/ws/payload.go

Names for metrics & labels should use valid characters for prometheus.
See: https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels

fix: use underscore in labels

---

go.mod
go.sum

This chore updates goks to use the latest which is internally using the forked Kong repos for gohper-lua and gopher-json. The changes are required simultaneously due to underlying changes in the gopher-lua options to provide a patch upstream for this feature.

chore: bump goks and use Kong repos for gopher-lua and gopher-json

---

Makefile
libraries.mk
scripts/build-library.sh

the `build-libary.sh` script pulls the actual build script from go-atc router.
this PR makes it use the version pinned in go.mod, not only for version consistency but also makes the cache key correct, as it's built from the hash of go.mod

build: pull proper version of library build script
